const tg=async(e,m,b={})=>(await fetch("https://api.telegram.org/bot"+e.BOT_TOKEN+"/"+m,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)})).json();
const out=x=>new Response(JSON.stringify(x),{status:200,headers:{"content-type":"application/json"}});
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const admin=(e,id)=>String(e.ADMIN_ID||"").split(",").map(x=>x.trim()).filter(Boolean).includes(String(id));
const HOME="Arghavanplaylistt";

const ensure=async e=>{
 await e.DB.prepare("CREATE TABLE IF NOT EXISTS home_archive_posts(message_id INTEGER PRIMARY KEY,channel TEXT NOT NULL DEFAULT 'Arghavanplaylistt',url TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',future_dossier INTEGER NOT NULL DEFAULT 0,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();
 await e.DB.prepare("CREATE TABLE IF NOT EXISTS classification_categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,parent_id INTEGER,emoji TEXT,emoji_id TEXT,sort_order INTEGER NOT NULL DEFAULT 0)").run();
 await e.DB.prepare("CREATE UNIQUE INDEX IF NOT EXISTS classification_categories_sibling_name ON classification_categories(COALESCE(parent_id,0),name)").run();
 await e.DB.prepare("CREATE INDEX IF NOT EXISTS classification_categories_parent_order ON classification_categories(parent_id,sort_order,id)").run();
 await e.DB.prepare("CREATE TABLE IF NOT EXISTS home_post_paths(id INTEGER PRIMARY KEY AUTOINCREMENT,post_id INTEGER NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();
 await e.DB.prepare("CREATE INDEX IF NOT EXISTS home_post_paths_post ON home_post_paths(post_id,sort_order,id)").run();
 await e.DB.prepare("CREATE TABLE IF NOT EXISTS home_post_path_nodes(path_id INTEGER NOT NULL,level INTEGER NOT NULL,category_id INTEGER NOT NULL,PRIMARY KEY(path_id,level),UNIQUE(path_id,category_id))").run();
 await e.DB.prepare("CREATE INDEX IF NOT EXISTS home_post_path_nodes_category ON home_post_path_nodes(category_id,path_id)").run();
 await e.DB.prepare("CREATE TABLE IF NOT EXISTS home_post_keywords(post_id INTEGER NOT NULL,keyword TEXT NOT NULL,PRIMARY KEY(post_id,keyword))").run();
 await e.DB.prepare("CREATE TABLE IF NOT EXISTS classification_settings(id INTEGER PRIMARY KEY CHECK(id=1),enabled INTEGER NOT NULL DEFAULT 1,library_enabled INTEGER NOT NULL DEFAULT 0,next_message_id INTEGER NOT NULL DEFAULT 1,last_message_id INTEGER NOT NULL DEFAULT 0)").run();
 await e.DB.prepare("CREATE TABLE IF NOT EXISTS user_library_preferences(user_id INTEGER PRIMARY KEY,sort_mode TEXT NOT NULL DEFAULT 'cercis',updated_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();
 try{await e.DB.prepare("ALTER TABLE classification_settings ADD COLUMN library_enabled INTEGER NOT NULL DEFAULT 0").run()}catch{}
 await e.DB.prepare("INSERT OR IGNORE INTO classification_settings(id) VALUES(1)").run();
 const n=await e.DB.prepare("SELECT COUNT(*) n FROM classification_categories").first();
 if(!Number(n?.n))for(const [name,emoji,sort] of [["🎵 موسیقی","🎵",1],["📖 نقل‌قول","📖",2],["🖼 تصویر","🖼",3],["🎬 ویدیو","🎬",4],["💭 نوشته","💭",5],["🌅 Daily","🌅",6]])await e.DB.prepare("INSERT OR IGNORE INTO classification_categories(name,emoji,sort_order) VALUES(?,?,?)").bind(name,emoji,sort).run();
};

const setting=async e=>e.DB.prepare("SELECT * FROM classification_settings WHERE id=1").first();
const children=async(e,parent,mode="cercis")=>{
 if(mode==="count"){
  const sql="WITH RECURSIVE tree(root,id) AS (SELECT id,id FROM classification_categories UNION ALL SELECT t.root,c.id FROM classification_categories c JOIN tree t ON c.parent_id=t.id) SELECT c.*,COUNT(DISTINCT pp.post_id) n FROM classification_categories c LEFT JOIN tree t ON t.root=c.id LEFT JOIN home_post_path_nodes pn ON pn.category_id=t.id LEFT JOIN home_post_paths pp ON pp.id=pn.path_id "+(parent==null?"WHERE c.parent_id IS NULL":"WHERE c.parent_id=?")+" GROUP BY c.id ORDER BY n DESC,c.sort_order ASC,c.id ASC";
  const r=parent==null?await e.DB.prepare(sql).all():await e.DB.prepare(sql).bind(parent).all();return r.results||[];
 }
 const order=mode==="alphabetical"?"name COLLATE NOCASE ASC,sort_order ASC,id ASC":"sort_order ASC,id ASC";
 const sql=parent==null?"SELECT * FROM classification_categories WHERE parent_id IS NULL ORDER BY "+order:"SELECT * FROM classification_categories WHERE parent_id=? ORDER BY "+order;
 const r=parent==null?await e.DB.prepare(sql).all():await e.DB.prepare(sql).bind(parent).all();return r.results||[];
};
const postPaths=async(e,postId)=>((await e.DB.prepare("SELECT p.id,p.sort_order,p.created_at,(SELECT GROUP_CONCAT(c.name,' → ') FROM home_post_path_nodes n JOIN classification_categories c ON c.id=n.category_id WHERE n.path_id=p.id ORDER BY n.level) path FROM home_post_paths p WHERE p.post_id=? ORDER BY p.sort_order,p.id").bind(postId).all()).results||[]);
const pathNodes=async(e,pathId)=>((await e.DB.prepare("SELECT n.level,n.category_id,c.name,c.parent_id FROM home_post_path_nodes n JOIN classification_categories c ON c.id=n.category_id WHERE n.path_id=? ORDER BY n.level").bind(pathId).all()).results||[]);
const createPath=async(e,postId)=>{const mx=await e.DB.prepare("SELECT COALESCE(MAX(sort_order),0) n FROM home_post_paths WHERE post_id=?").bind(postId).first();const r=await e.DB.prepare("INSERT INTO home_post_paths(post_id,sort_order) VALUES(?,?) RETURNING id").bind(postId,Number(mx?.n||0)+1).first();return Number(r?.id||0);};
const dossierMark=async(e,postId)=>{try{const direct=await e.DB.prepare("SELECT 1 FROM tracks WHERE post_id=? LIMIT 1").bind(postId).first();if(direct)return" *";const linked=await e.DB.prepare("SELECT 1 FROM track_links l JOIN tracks t ON t.id=l.track_id WHERE l.post_id=? LIMIT 1").bind(postId).first();return linked?" *":""}catch{return""}};

const render=async(e,q)=>{
 await ensure(e);const s=await setting(e),id=Number(s.next_message_id||1),r=await e.DB.prepare("SELECT * FROM home_archive_posts WHERE message_id=?").bind(id).first(),paths=await postPaths(e,id),mark=await dossierMark(e,id);
 const status=r?.status==="deleted"?"🔴 حذف‌شده":paths.length?"🟢 طبقه‌بندی‌شده":"🟡 آماده بررسی";
 const pathText=paths.length?paths.map((x,i)=>String(i+1)+". "+(x.path||"—")).join("\n"):"هنوز مسیری ثبت نشده است";
 const text="⚙️ <b>موتور پیشرفته طبقه‌بندی</b>\n\n📌 پست #"+id+mark+"\n🔗 <a href=\"https://t.me/"+HOME+"/"+id+"\">مشاهده پست</a>\n\nوضعیت: "+status+"\n\n<b>🗂 مسیرهای کتابخانه:</b>\n"+esc(pathText);
 const kb=[[{text:"👀 مشاهده پست",url:"https://t.me/"+HOME+"/"+id}],[{text:"🗂 مسیرهای پست",callback_data:"ce_paths:"+id},{text:"🌳 مدیریت ساختار",callback_data:"ce_tree"}],[{text:"🔑 کلیدواژه",callback_data:"ce_kw:"+id}],[{text:"❤️ صف پرونده‌های آینده",callback_data:"ce_future:"+id}],[{text:"❌ پست حذف شده",callback_data:"ce_deleted:"+id}],[{text:"◀️ قبلی",callback_data:"ce_prev:"+id},{text:"بعدی ▶️",callback_data:"ce_next:"+id}],[{text:s.enabled?"⏸ خاموش کردن موتور":"▶️ روشن کردن موتور",callback_data:"ce_toggle"}],[{text:s.library_enabled?"🔴 مخفی‌کردن کتابخانه از Start":"🟢 نمایش کتابخانه در Start",callback_data:"ce_library_toggle"}],[{text:"🔙 پنل مدیریت",callback_data:"panel"}]];
 return out(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text,parse_mode:"HTML",reply_markup:{inline_keyboard:kb}}));
};

const pathList=async(e,q,postId)=>{
 const paths=await postPaths(e,postId);
 const buttons=paths.map((x,i)=>[{text:""+(i+1)+"️⃣ "+(x.path||"مسیر خالی"),callback_data:"ce_path_edit:"+postId+":"+x.id+":1"}]);
 buttons.push([{text:"➕ افزودن مسیر",callback_data:"ce_path_add:"+postId}]);
 if(paths.length)buttons.push([{text:"✏️ مدیریت مسیرها",callback_data:"ce_path_manage:"+postId}]);
 buttons.push([{text:"🔙 موتور طبقه‌بندی",callback_data:"classification_engine"}]);
 return out(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text:"🗂 <b>مسیرهای پست #"+postId+"</b>\n\n"+(paths.length?paths.map((x,i)=>String(i+1)+". "+esc(x.path||"—")).join("\n"):"هنوز مسیری ثبت نشده است"),parse_mode:"HTML",reply_markup:{inline_keyboard:buttons}}));
};

const pathMenu=async(e,q,postId,pathId,level)=>{
 const rows=await pathNodes(e,pathId),current=rows.find(x=>Number(x.level)===level),parent=level===1?null:Number(rows.find(x=>Number(x.level)===level-1)?.category_id||0)||null,cs=await children(e,parent);
 const buttons=cs.map(x=>[{text:(Number(current?.category_id)===Number(x.id)?"✅ ":"")+x.name,callback_data:"ce_pick:"+postId+":"+pathId+":"+level+":"+x.id}]);
 if(level>1)buttons.push([{text:"⬅️ سطح قبل",callback_data:"ce_path_edit:"+postId+":"+pathId+":"+(level-1)}]);
 buttons.push([{text:"➕ طبقه جدید",callback_data:"ce_newcat:"+postId+":"+pathId+":"+level+":"+(parent||0)}]);
 if(current)buttons.push([{text:"➕ افزودن سطح بعدی",callback_data:"ce_path_edit:"+postId+":"+pathId+":"+(level+1)}]);
 buttons.push([{text:"✅ ذخیره این مسیر",callback_data:"ce_path_done:"+postId+":"+pathId}],[{text:"🗑 حذف این مسیر",callback_data:"ce_path_delete:"+postId+":"+pathId}],[{text:"🔙 فهرست مسیرها",callback_data:"ce_paths:"+postId}]);
 const shown=rows.length?rows.map(x=>x.name).join(" → "):"هنوز انتخابی نشده";
 return out(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text:"🗂 <b>ویرایش مسیر پست #"+postId+"</b>\n\nمسیر فعلی: "+esc(shown)+"\n\n<b>سطح "+level+"</b> را انتخاب کن:",parse_mode:"HTML",reply_markup:{inline_keyboard:buttons}}));
};

const newCategoryPrompt=async(e,q,postId,pathId,level,parent)=>{
 await e.DB.prepare("INSERT INTO sessions(user_id,step,channel,post_id,url,draft,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET step=excluded.step,channel=excluded.channel,post_id=excluded.post_id,url=excluded.url,draft=excluded.draft,updated_at=CURRENT_TIMESTAMP").bind(q.from.id,"CLASSIFY_NEWCAT",HOME,postId,"https://t.me/"+HOME+"/"+postId,JSON.stringify({post_id:postId,path_id:pathId,level,parent:Number(parent)||null,message_id:Number(q.message?.message_id||0)})).run();
 return out(await tg(e,"sendMessage",{chat_id:q.message.chat.id,text:"➕ نام طبقهٔ جدید برای سطح "+level+" را بفرست."}));
};
const keywordPrompt=async(e,q,id)=>{await e.DB.prepare("INSERT INTO sessions(user_id,step,channel,post_id,url,draft,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET step=excluded.step,channel=excluded.channel,post_id=excluded.post_id,url=excluded.url,draft=excluded.draft,updated_at=CURRENT_TIMESTAMP").bind(q.from.id,"CLASSIFY_KEYWORDS",HOME,id,"https://t.me/"+HOME+"/"+id,null).run();return out(await tg(e,"sendMessage",{chat_id:q.message.chat.id,text:"🔑 کلیدواژه‌ها را در یک پیام بنویس. با ویرگول یا خط جدید جدا کن."}));};

const treeRoot=async(e,q)=>{const cs=await children(e,null),buttons=cs.map(c=>[{text:c.name,callback_data:"ce_tree_cat:"+c.id}]);buttons.push([{text:"➕ طبقه اصلی جدید",callback_data:"ce_tree_new:0"}],[{text:"🔙 موتور طبقه‌بندی",callback_data:"classification_engine"}]);return out(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text:"🌳 <b>مدیریت ساختار کتابخانه</b>\n\nطبقه‌های اصلی کتابخانه:",parse_mode:"HTML",reply_markup:{inline_keyboard:buttons}}));};
const treeCat=async(e,q,cid)=>{const c=await e.DB.prepare("SELECT * FROM classification_categories WHERE id=?").bind(cid).first();if(!c)return treeRoot(e,q);const sub=await children(e,cid),buttons=sub.map(x=>[{text:x.name,callback_data:"ce_tree_cat:"+x.id}]);buttons.push([{text:"➕ زیرطبقه جدید",callback_data:"ce_tree_new:"+cid}],[{text:"✏️ تغییر نام",callback_data:"ce_tree_rename:"+cid}],[{text:"↕️ تغییر ترتیب",callback_data:"ce_tree_order:"+cid}],[{text:"🗑 حذف طبقه",callback_data:"ce_tree_delete:"+cid}]);if(c.parent_id!=null)buttons.push([{text:"⬆️ بازگشت به والد",callback_data:"ce_tree_cat:"+c.parent_id}]);else buttons.push([{text:"⬅️ فهرست طبقات اصلی",callback_data:"ce_tree"}]);return out(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text:"🌳 <b>ساختار کتابخانه</b>\n\nمسیر: <b>"+esc(c.name)+"</b>\n\nزیرطبقه‌ها: "+(sub.length||"ندارد"),parse_mode:"HTML",reply_markup:{inline_keyboard:buttons}}));};
const treePrompt=async(e,q,step,cid,draft={})=>{await e.DB.prepare("INSERT INTO sessions(user_id,step,channel,post_id,url,draft,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET step=excluded.step,channel=excluded.channel,post_id=excluded.post_id,url=excluded.url,draft=excluded.draft,updated_at=CURRENT_TIMESTAMP").bind(q.from.id,step,HOME,cid||0,"https://t.me/"+HOME+"/"+(cid||0),JSON.stringify(draft)).run();const text=step==="CLASSIFY_TREE_RENAME"?"✏️ نام جدید این طبقه را بفرست.":step==="CLASSIFY_TREE_ORDER"?"↕️ عدد جابه‌جایی را بفرست؛ مثلاً 1 یا -1.":"➕ نام طبقهٔ جدید را بفرست.";return out(await tg(e,"sendMessage",{chat_id:q.message.chat.id,text}));};

const publicTree=async(e,q,parent)=>{
 const s=await setting(e);if(!Number(s.library_enabled))return out(await tg(e,"answerCallbackQuery",{callback_query_id:q.id,text:"کتابخانه فعلاً فعال نیست."}));
 const pref=await e.DB.prepare("SELECT sort_mode FROM user_library_preferences WHERE user_id=?").bind(q.from.id).first();const mode=parent==null?"cercis":String(pref?.sort_mode||"cercis"),cs=await children(e,parent,mode),buttons=cs.map(c=>[{text:c.name+(mode==="count"?" ("+Number(c.n||0)+")":""),callback_data:"home_cat:"+c.id}]);buttons.push([{text:"⚙️ نحوه نمایش",callback_data:"home_sort"}]);if(parent!=null)buttons.push([{text:"🔙 بازگشت",callback_data:"home_categories"}]);else buttons.push([{text:"🔙 منوی اصلی",callback_data:"public_start"}]);return out(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text:"🗂 <b>کتابخانه Home</b>\n\nیک شاخه را انتخاب کن:",parse_mode:"HTML",reply_markup:{inline_keyboard:buttons}}));
};
const publicCategory=async(e,q,cid,page=0,subPage=0)=>{
 const s=await setting(e);if(!Number(s.library_enabled))return out(await tg(e,"answerCallbackQuery",{callback_query_id:q.id,text:"کتابخانه فعلاً فعال نیست."}));
 const c=await e.DB.prepare("SELECT * FROM classification_categories WHERE id=?").bind(cid).first();if(!c)return out({ok:true});
 const pref=await e.DB.prepare("SELECT sort_mode FROM user_library_preferences WHERE user_id=?").bind(q.from.id).first(),mode=String(pref?.sort_mode||"cercis"),allSub=await children(e,cid,mode),subLimit=15,subOffset=Math.max(0,Number(subPage)||0)*subLimit,sub=allSub.slice(subOffset,subOffset+subLimit),subHasNext=allSub.length>subOffset+subLimit,limit=20,offset=Math.max(0,Number(page)||0)*limit;
 const rows=(await e.DB.prepare("SELECT DISTINCT p.message_id,p.url FROM home_archive_posts p JOIN home_post_paths pp ON pp.post_id=p.message_id JOIN home_post_path_nodes pn ON pn.path_id=pp.id WHERE pn.category_id=? AND p.status!='deleted' AND NOT EXISTS (SELECT 1 FROM home_post_path_nodes next WHERE next.path_id=pn.path_id AND next.level>pn.level) ORDER BY p.message_id DESC LIMIT ? OFFSET ?").bind(cid,limit+1,offset).all()).results||[];
 const hasNext=rows.length>limit;rows.splice(limit);
 const posts=[];for(const p of rows){const mark=await dossierMark(e,p.message_id);posts.push({...p,mark})}
 const buttons=sub.map(x=>[{text:x.name+(mode==="count"?" ("+Number(x.n||0)+")":""),callback_data:"home_cat:"+x.id}]);
 const subNav=[];if(subPage>0)subNav.push({text:"◀️ شاخه‌های قبل",callback_data:"home_cat_sub_page:"+cid+":"+(subPage-1)+":"+page});if(subHasNext)subNav.push({text:"شاخه‌های بعد ▶️",callback_data:"home_cat_sub_page:"+cid+":"+(subPage+1)+":"+page});if(subNav.length)buttons.push(subNav);
 buttons.push(...posts.map(x=>[{text:"📌 پست #"+x.message_id+x.mark,url:x.url}]));
 const nav=[];if(page>0)nav.push({text:"◀️ پست‌های قبل",callback_data:"home_cat_page:"+cid+":"+(page-1)+":"+subPage});if(hasNext)nav.push({text:"پست‌های بعد ▶️",callback_data:"home_cat_page:"+cid+":"+(page+1)+":"+subPage});if(nav.length)buttons.push(nav);
 buttons.push([{text:"⚙️ نحوه نمایش",callback_data:"home_sort:"+cid}],[{text:"🔙 بازگشت",callback_data:c.parent_id==null?"home_categories":"home_cat:"+c.parent_id}]);
 return out(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text:"🗂 <b>"+esc(c.name)+"</b>\n\n"+(allSub.length?"شاخه‌ها و پست‌های مستقیم این بخش:":"پست‌های مستقیم این بخش:"),parse_mode:"HTML",reply_markup:{inline_keyboard:buttons}}));
};
const sortMenu=async(e,q,parent)=>{const s=await setting(e);if(!Number(s.library_enabled))return out(await tg(e,"answerCallbackQuery",{callback_query_id:q.id,text:"کتابخانه فعلاً فعال نیست."}));const target=Number(parent)||0;const pref=await e.DB.prepare("SELECT sort_mode FROM user_library_preferences WHERE user_id=?").bind(q.from.id).first(),current=String(pref?.sort_mode||"cercis"),cb=m=>"home_sort_set:"+m+":"+target;return out(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text:"⚙️ <b>نحوه نمایش</b>\n\nترتیب فعلی را انتخاب کن:",parse_mode:"HTML",reply_markup:{inline_keyboard:[[{text:current==="cercis"?"🟢 ترتیب سرسیس":"⚪ ترتیب سرسیس",callback_data:cb("cercis")}],[{text:current==="alphabetical"?"🟢 الفبایی":"⚪ الفبایی",callback_data:cb("alphabetical")}],[{text:current==="count"?"🟢 بر اساس تعداد":"⚪ بر اساس تعداد",callback_data:cb("count")}],[{text:"🔙 بازگشت",callback_data:target?"home_cat:"+target:"home_categories"}]]}}))};

export default{async fetch(req,e){
 let u;try{u=await req.clone().json()}catch{return out({ok:true})}
 const q=u.callback_query,m=u.message,id=q?.from?.id||m?.from?.id,d=String(q?.data||"");await ensure(e);
 if(q&&(d==="home_categories"||d.startsWith("home_cat:")||d.startsWith("home_cat_page:")||d.startsWith("home_cat_sub_page:")||d==="home_sort"||d.startsWith("home_sort:")||d.startsWith("home_sort_set:"))){
  if(d==="home_sort"||d.startsWith("home_sort:"))return sortMenu(e,q,d==="home_sort"?0:d.split(":")[1]);
  if(d.startsWith("home_sort_set:")){const [,mode,targetRaw]=d.split(":"),target=Number(targetRaw)||0;if(!["cercis","alphabetical","count"].includes(mode))return out({ok:true});await e.DB.prepare("INSERT INTO user_library_preferences(user_id,sort_mode,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET sort_mode=excluded.sort_mode,updated_at=CURRENT_TIMESTAMP").bind(id,mode).run();await tg(e,"answerCallbackQuery",{callback_query_id:q.id,text:"نحوه نمایش ذخیره شد."});return target?publicCategory(e,q,target,0):publicTree(e,q,null);}
  await tg(e,"answerCallbackQuery",{callback_query_id:q.id});if(d==="home_categories")return publicTree(e,q,null);if(d.startsWith("home_cat_page:")){const [,cid,page,subPage]=d.split(":");return publicCategory(e,q,Number(cid),Number(page)||0,Number(subPage)||0)}if(d.startsWith("home_cat_sub_page:")){const [,cid,subPage,page]=d.split(":");return publicCategory(e,q,Number(cid),Number(page)||0,Number(subPage)||0)}return publicCategory(e,q,Number(d.split(":")[1]),0,0);
 }
 if(!admin(e,id))return out({ok:true});
 if(m){const s=await e.DB.prepare("SELECT * FROM sessions WHERE user_id=?").bind(id).first();
  if(s?.step==="CLASSIFY_TREE_NEWCAT"){const name=String(m.text||"").trim();let meta={};try{meta=JSON.parse(String(s.draft||"{}"))}catch{};if(!name)return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ نام طبقه را بفرست."}));const parent=Number(meta.parent)||null;const mx=await e.DB.prepare("SELECT COALESCE(MAX(sort_order),0) n FROM classification_categories WHERE parent_id IS ?").bind(parent).first();try{await e.DB.prepare("INSERT INTO classification_categories(name,parent_id,sort_order) VALUES(?,?,?)").bind(name,parent,Number(mx?.n||0)+1).run()}catch{return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ طبقه‌ای با این نام در همین سطح از قبل وجود دارد."}))}const c=await e.DB.prepare("SELECT id FROM classification_categories WHERE parent_id IS ? AND name=? ORDER BY id DESC LIMIT 1").bind(parent,name).first();await e.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(id).run();return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"✅ طبقهٔ «"+esc(name)+"» ساخته شد.",reply_markup:{inline_keyboard:[[{text:"🌳 باز کردن ساختار",callback_data:"ce_tree_cat:"+c.id}]]}}));}
  if(s?.step==="CLASSIFY_TREE_RENAME"){const name=String(m.text||"").trim();if(!name)return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ نام طبقه را بفرست."}));let meta={};try{meta=JSON.parse(String(s.draft||"{}"))}catch{};const cid=Number(meta.category_id);const c=await e.DB.prepare("SELECT parent_id FROM classification_categories WHERE id=?").bind(cid).first();try{await e.DB.prepare("UPDATE classification_categories SET name=? WHERE id=?").bind(name,cid).run()}catch{return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ طبقه‌ای با این نام در همین سطح از قبل وجود دارد."}))}await e.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(id).run();return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"✅ نام طبقه تغییر کرد.",reply_markup:{inline_keyboard:[[{text:"🌳 باز کردن ساختار",callback_data:"ce_tree_cat:"+cid}]]}}));}
  if(s?.step==="CLASSIFY_TREE_ORDER"){const delta=Number(String(m.text||"").trim());let meta={};try{meta=JSON.parse(String(s.draft||"{}"))}catch{};const cid=Number(meta.category_id);if(!Number.isInteger(delta)||!delta||Math.abs(delta)>20)return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ یک عدد صحیح غیرصفر بفرست."}));const c=await e.DB.prepare("SELECT * FROM classification_categories WHERE id=?").bind(cid).first();if(!c)return out({ok:true});const sib=(await e.DB.prepare("SELECT id,sort_order FROM classification_categories WHERE parent_id IS ? ORDER BY sort_order,id").bind(c.parent_id).all()).results||[];const idx=sib.findIndex(x=>Number(x.id)===cid),to=Math.max(0,Math.min(sib.length-1,idx+delta));const [mv]=sib.splice(idx,1);sib.splice(to,0,mv);for(let i=0;i<sib.length;i++)await e.DB.prepare("UPDATE classification_categories SET sort_order=? WHERE id=?").bind(i+1,sib[i].id).run();await e.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(id).run();return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"✅ ترتیب اصلاح شد.",reply_markup:{inline_keyboard:[[{text:"🌳 باز کردن ساختار",callback_data:"ce_tree_cat:"+cid}]]}}));}
  if(s?.step==="CLASSIFY_NEWCAT"){const name=String(m.text||"").trim();let meta={};try{meta=JSON.parse(String(s.draft||"{}"))}catch{};if(!name)return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ نام طبقه را بفرست."}));const parent=Number(meta.parent)||null;const mx=await e.DB.prepare("SELECT COALESCE(MAX(sort_order),0) n FROM classification_categories WHERE parent_id IS ?").bind(parent).first();let c;try{await e.DB.prepare("INSERT INTO classification_categories(name,parent_id,sort_order) VALUES(?,?,?)").bind(name,parent,Number(mx?.n||0)+1).run();c=await e.DB.prepare("SELECT id FROM classification_categories WHERE parent_id IS ? AND name=? ORDER BY id DESC LIMIT 1").bind(parent,name).first()}catch{return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ طبقه‌ای با این نام در همین سطح وجود دارد."}))}const pathId=Number(meta.path_id);await e.DB.prepare("DELETE FROM home_post_path_nodes WHERE path_id=? AND level>=?").bind(pathId,Number(meta.level||1)).run();await e.DB.prepare("INSERT INTO home_post_path_nodes(path_id,level,category_id) VALUES(?,?,?)").bind(pathId,Number(meta.level||1),Number(c.id)).run();await e.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(id).run();const fakeQ={message:{chat:{id:m.chat.id},message_id:Number(meta.message_id||0)},from:m.from};if(fakeQ.message.message_id)return pathMenu(e,fakeQ,Number(meta.post_id),pathId,Number(meta.level||1));return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"🗂 مسیر به‌روزرسانی شد."}));}
  if(s?.step==="CLASSIFY_KEYWORDS"){const words=String(m.text||"").split(/[,،\n]/).map(x=>x.trim()).filter(Boolean);await e.DB.prepare("DELETE FROM home_post_keywords WHERE post_id=?").bind(Number(s.post_id)).run();for(const w of [...new Set(words)])await e.DB.prepare("INSERT OR IGNORE INTO home_post_keywords(post_id,keyword) VALUES(?,?)").bind(Number(s.post_id),w).run();await e.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(id).run();const paths=await postPaths(e,Number(s.post_id));await e.DB.prepare("INSERT OR REPLACE INTO home_archive_posts(message_id,channel,url,status,updated_at) VALUES(?,?,?,'pending',CURRENT_TIMESTAMP)").bind(Number(s.post_id),HOME,"https://t.me/"+HOME+"/"+s.post_id).run();await e.DB.prepare("UPDATE classification_settings SET last_message_id=?,next_message_id=? WHERE id=1").bind(Number(s.post_id),Number(s.post_id)+1).run();return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"✅ "+words.length+" کلیدواژه ذخیره شد.\n\n📌 پست #"+(Number(s.post_id)+1)+" آمادهٔ بررسی است.",reply_markup:{inline_keyboard:[[{text:"▶️ رفتن به پست بعدی",callback_data:"ce_continue"}],[{text:"⚙️ باز کردن موتور",callback_data:"classification_engine"}]]}}));}
  return out({ok:true});
 }
 await tg(e,"answerCallbackQuery",{callback_query_id:q.id});
 if(d==="classification_engine"||d==="ce_continue")return render(e,q);
 if(d==="ce_tree")return treeRoot(e,q);
 if(d.startsWith("ce_tree_cat:"))return treeCat(e,q,Number(d.split(":")[1]));
 if(d.startsWith("ce_tree_new:"))return treePrompt(e,q,"CLASSIFY_TREE_NEWCAT",Number(d.split(":")[1])||null,{parent:Number(d.split(":")[1])||null});
 if(d.startsWith("ce_tree_rename:"))return treePrompt(e,q,"CLASSIFY_TREE_RENAME",Number(d.split(":")[1]),{category_id:Number(d.split(":")[1])});
 if(d.startsWith("ce_tree_order:"))return treePrompt(e,q,"CLASSIFY_TREE_ORDER",Number(d.split(":")[1]),{category_id:Number(d.split(":")[1])});
 if(d.startsWith("ce_tree_delete:")){const cid=Number(d.split(":")[1]),c=await e.DB.prepare("SELECT * FROM classification_categories WHERE id=?").bind(cid).first();if(!c)return treeRoot(e,q);const child=await e.DB.prepare("SELECT 1 FROM classification_categories WHERE parent_id=? LIMIT 1").bind(cid).first(),dep=await e.DB.prepare("SELECT 1 FROM home_post_path_nodes WHERE category_id=? LIMIT 1").bind(cid).first();if(child||dep)return out(await tg(e,"answerCallbackQuery",{callback_query_id:q.id,text:"❌ این طبقه زیرشاخه یا مسیر وابسته دارد و فعلاً قابل حذف نیست.",show_alert:true}));await e.DB.prepare("DELETE FROM classification_categories WHERE id=?").bind(cid).run();return c.parent_id==null?treeRoot(e,q):treeCat(e,q,c.parent_id);}
 if(d==="ce_toggle"){const s=await setting(e);await e.DB.prepare("UPDATE classification_settings SET enabled=? WHERE id=1").bind(s.enabled?0:1).run();return render(e,q);}
 if(d==="ce_library_toggle"){const s=await setting(e);await e.DB.prepare("UPDATE classification_settings SET library_enabled=? WHERE id=1").bind(s.library_enabled?0:1).run();return render(e,q);}
 if(d.startsWith("ce_paths:"))return pathList(e,q,Number(d.split(":")[1]));
 if(d.startsWith("ce_path_add:")){const pid=Number(d.split(":")[1]),pathId=await createPath(e,pid);return pathMenu(e,q,pid,pathId,1);}
 if(d.startsWith("ce_path_edit:")){const a=d.split(":").map(Number);return pathMenu(e,q,a[1],a[2],a[3]||1);}
 if(d.startsWith("ce_path_manage:")){const pid=Number(d.split(":")[1]),paths=await postPaths(e,pid),buttons=paths.map((x,i)=>[{text:"✏️ مسیر "+(i+1),callback_data:"ce_path_edit:"+pid+":"+x.id+":1"},{text:"🗑",callback_data:"ce_path_delete:"+pid+":"+x.id}]);buttons.push([{text:"🔙 بازگشت",callback_data:"ce_paths:"+pid}]);return out(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text:"✏️ <b>مدیریت مسیرهای پست #"+pid+"</b>",parse_mode:"HTML",reply_markup:{inline_keyboard:buttons}}));}
 if(d.startsWith("ce_pick:")){const [,pid,pathId,level,cid]=d.split(":").map(Number);const parent=Number(level)>1?await e.DB.prepare("SELECT category_id FROM home_post_path_nodes WHERE path_id=? AND level=?").bind(pathId,level-1).first():null;const cat=await e.DB.prepare("SELECT parent_id FROM classification_categories WHERE id=?").bind(cid).first();if(Number(level)>1&&(!parent||Number(parent.category_id)!==Number(cat?.parent_id)))return pathMenu(e,q,pid,pathId,level);await e.DB.prepare("DELETE FROM home_post_path_nodes WHERE path_id=? AND level>=?").bind(pathId,level).run();await e.DB.prepare("INSERT INTO home_post_path_nodes(path_id,level,category_id) VALUES(?,?,?)").bind(pathId,level,cid).run();return pathMenu(e,q,pid,pathId,level);}
 if(d.startsWith("ce_path_done:")){const a=d.split(":").map(Number),paths=await pathNodes(e,a[2]);if(!paths.length)return out(await tg(e,"answerCallbackQuery",{callback_query_id:q.id,text:"❌ این مسیر هنوز خالی است.",show_alert:true}));return pathList(e,q,a[1]);}
 if(d.startsWith("ce_path_delete:")){const a=d.split(":").map(Number);await e.DB.prepare("DELETE FROM home_post_path_nodes WHERE path_id=?").bind(a[2]).run();await e.DB.prepare("DELETE FROM home_post_paths WHERE id=?").bind(a[2]).run();return pathList(e,q,a[1]);}
 if(d.startsWith("ce_newcat:")){const a=d.split(":").map(Number);return newCategoryPrompt(e,q,a[1],a[2],a[3],a[4]||0);}
 if(d.startsWith("ce_kw:"))return keywordPrompt(e,q,Number(d.split(":")[1]));
 if(d.startsWith("ce_deleted:")){const n=Number(d.split(":")[1]);await e.DB.prepare("INSERT OR REPLACE INTO home_archive_posts(message_id,channel,url,status,updated_at) VALUES(?,?,?,'deleted',CURRENT_TIMESTAMP)").bind(n,HOME,"https://t.me/"+HOME+"/"+n).run();await e.DB.prepare("DELETE FROM home_post_path_nodes WHERE path_id IN (SELECT id FROM home_post_paths WHERE post_id=?)").bind(n).run();await e.DB.prepare("DELETE FROM home_post_paths WHERE post_id=?").bind(n).run();await e.DB.prepare("UPDATE classification_settings SET last_message_id=?,next_message_id=? WHERE id=1").bind(n,n+1).run();return render(e,q);}
 if(d.startsWith("ce_future:")){const n=Number(d.split(":")[1]);await e.DB.prepare("INSERT OR REPLACE INTO home_archive_posts(message_id,channel,url,status,future_dossier,updated_at) VALUES(?,?,?,'pending',1,CURRENT_TIMESTAMP)").bind(n,HOME,"https://t.me/"+HOME+"/"+n).run();return render(e,q);}
 if(d.startsWith("ce_next:")){const n=Number(d.split(":")[1])+1;await e.DB.prepare("UPDATE classification_settings SET next_message_id=? WHERE id=1").bind(n).run();return render(e,q);}
 if(d.startsWith("ce_prev:")){const n=Math.max(1,Number(d.split(":")[1])-1);await e.DB.prepare("UPDATE classification_settings SET next_message_id=? WHERE id=1").bind(n).run();return render(e,q);}
 if(d.startsWith("ce_back:"))return render(e,q);
 return out({ok:true});
}};