const tg=async(e,m,b={})=>(await fetch(`https://api.telegram.org/bot${e.BOT_TOKEN}/${m}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)})).json();
const out=x=>new Response(JSON.stringify(x),{status:200,headers:{"content-type":"application/json"}});
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const admin=(e,id)=>String(e.ADMIN_ID||"").split(",").map(x=>x.trim()).filter(Boolean).includes(String(id));
const HOME="Arghavanplaylistt";
const ensure=async e=>{
 await e.DB.prepare(`CREATE TABLE IF NOT EXISTS home_archive_posts(message_id INTEGER PRIMARY KEY,channel TEXT NOT NULL DEFAULT 'Arghavanplaylistt',url TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',future_dossier INTEGER NOT NULL DEFAULT 0,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run();
 await e.DB.prepare(`CREATE TABLE IF NOT EXISTS classification_categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE,parent_id INTEGER,emoji TEXT,emoji_id TEXT,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)`).run();
 await e.DB.prepare(`CREATE TABLE IF NOT EXISTS home_post_categories(post_id INTEGER NOT NULL,category_id INTEGER NOT NULL,PRIMARY KEY(post_id,category_id))`).run();
 await e.DB.prepare(`CREATE TABLE IF NOT EXISTS home_post_keywords(post_id INTEGER NOT NULL,keyword TEXT NOT NULL,PRIMARY KEY(post_id,keyword))`).run();
 await e.DB.prepare(`CREATE TABLE IF NOT EXISTS classification_settings(id INTEGER PRIMARY KEY CHECK(id=1),enabled INTEGER NOT NULL DEFAULT 1,next_message_id INTEGER NOT NULL DEFAULT 1,last_message_id INTEGER NOT NULL DEFAULT 0)`).run();
 await e.DB.prepare("INSERT OR IGNORE INTO classification_settings(id) VALUES(1)").run();
 const n=await e.DB.prepare("SELECT COUNT(*) n FROM classification_categories").first();
 if(!Number(n?.n)){for(const [name,emoji,sort] of [["🎵 موسیقی","🎵",1],["📖 نقل‌قول","📖",2],["🖼 تصویر","🖼",3],["🎬 ویدیو","🎬",4],["💭 نوشته","💭",5],["🌅 Daily","🌅",6]])await e.DB.prepare("INSERT OR IGNORE INTO classification_categories(name,emoji,sort_order) VALUES(?,?,?)").bind(name,emoji,sort).run();}
};
const setting=async e=>e.DB.prepare("SELECT * FROM classification_settings WHERE id=1").first();
const categories=async e=>((await e.DB.prepare("SELECT * FROM classification_categories WHERE active=1 ORDER BY sort_order,id").all()).results||[]);
const render=async(e,q)=>{
 await ensure(e); const s=await setting(e),id=Number(s.next_message_id||1),r=await e.DB.prepare("SELECT * FROM home_archive_posts WHERE message_id=?").bind(id).first();
 const status=r?.status==="deleted"?"🔴 حذف‌شده":r?.status==="classified"?"🟢 طبقه‌بندی‌شده":"🟡 آماده بررسی";
 const text=`⚙️ <b>موتور پیشرفته طبقه‌بندی</b>\n\n📌 پست #${id}\n🔗 <a href="https://t.me/${HOME}/${id}">مشاهده پست</a>\n\nوضعیت: ${status}\n\n📝 پیش‌فرض این است که پست وجود دارد؛ فقط اگر واقعاً حذف شده بود، «پست حذف شده» را بزن.`;
 const kb=[[{text:"👀 مشاهده پست",url:`https://t.me/${HOME}/${id}`}],[{text:"📂 دسته‌بندی",callback_data:`ce_cat:${id}`},{text:"🔑 کلیدواژه",callback_data:`ce_kw:${id}`}],[{text:"❤️ صف پرونده‌های آینده",callback_data:`ce_future:${id}`}],[{text:"❌ پست حذف شده",callback_data:`ce_deleted:${id}`}],[{text:"◀️ قبلی",callback_data:`ce_prev:${id}`},{text:"بعدی ▶️",callback_data:`ce_next:${id}`}],[{text:s.enabled?"⏸ خاموش کردن موتور":"▶️ روشن کردن موتور",callback_data:"ce_toggle"}],[{text:"🔙 پنل مدیریت",callback_data:"panel"}]];
 return out(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text,parse_mode:"HTML",reply_markup:{inline_keyboard:kb}}));
};
const catMenu=async(e,q,id)=>{await ensure(e);const cs=await categories(e),rows=cs.map(c=>[{text:c.name,callback_data:`ce_setcat:${id}:${c.id}`}]);rows.push([{text:"➕ دسته‌بندی جدید",callback_data:`ce_newcat:${id}`}],[{text:"🔙 بازگشت",callback_data:`ce_back:${id}`}]);return out(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text:`📂 <b>دسته‌بندی پست #${id}</b>\n\nمی‌توانی چند دسته را همزمان انتخاب کنی؛ انتخاب دوباره حذفش می‌کند.`,parse_mode:"HTML",reply_markup:{inline_keyboard:rows}}))};
const keywordPrompt=async(e,q,id)=>{await e.DB.prepare("INSERT INTO sessions(user_id,step,channel,post_id,url,draft,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET step=excluded.step,channel=excluded.channel,post_id=excluded.post_id,url=excluded.url,draft=excluded.draft,updated_at=CURRENT_TIMESTAMP").bind(q.from.id,"CLASSIFY_KEYWORDS",HOME,id,`https://t.me/${HOME}/${id}`,null).run();return out(await tg(e,"sendMessage",{chat_id:q.message.chat.id,text:"🔑 کلیدواژه‌ها را در یک پیام بنویس. با ویرگول یا خط جدید جدا کن."}))};
export default{async fetch(req,e){let u;try{u=await req.clone().json()}catch{return out({ok:true})}const q=u.callback_query,m=u.message,id=q?.from?.id||m?.from?.id,d0=String(q?.data||"");await ensure(e);
 if(q && !admin(e,id) && (d0==="home_categories"||d0.startsWith("home_cat:"))){await tg(e,"answerCallbackQuery",{callback_query_id:q.id});const c=q.message.chat.id;if(d0==="home_categories"){const cs=await categories(e);return out(await tg(e,"editMessageText",{chat_id:c,message_id:q.message.message_id,text:"🗂 <b>طبقه‌بندی Home</b>\n\nیک دسته را انتخاب کن:",parse_mode:"HTML",reply_markup:{inline_keyboard:cs.map(x=>[{text:x.name,callback_data:"home_cat:"+x.id}]).concat([[{text:"🔙 منوی اصلی",callback_data:"public_start"}]])}}));}const cid=Number(d0.split(":")[1]),rows=(await e.DB.prepare("SELECT p.message_id,p.url FROM home_archive_posts p JOIN home_post_categories pc ON pc.post_id=p.message_id WHERE pc.category_id=? AND p.status!='deleted' ORDER BY p.message_id DESC LIMIT 20").bind(cid).all()).results||[];const cs=await e.DB.prepare("SELECT name FROM classification_categories WHERE id=?").bind(cid).first();const buttons=rows.map(x=>[{text:"📌 پست #"+x.message_id,url:x.url}]);buttons.push([{text:"🔙 دسته‌بندی‌ها",callback_data:"home_categories"}]);return out(await tg(e,"editMessageText",{chat_id:c,message_id:q.message.message_id,text:"🗂 <b>"+esc(cs?.name||"دسته‌بندی")+"</b>\n\nآخرین پست‌های ثبت‌شده:",parse_mode:"HTML",reply_markup:{inline_keyboard:buttons}}));}
if(!admin(e,id))return out({ok:true});if(m){const s=await e.DB.prepare("SELECT * FROM sessions WHERE user_id=?").bind(id).first();if(s?.step==="CLASSIFY_KEYWORDS"){const words=String(m.text||"").split(/[,،\n]/).map(x=>x.trim()).filter(Boolean);await e.DB.prepare("DELETE FROM home_post_keywords WHERE post_id=?").bind(Number(s.post_id)).run();for(const w of [...new Set(words)])await e.DB.prepare("INSERT OR IGNORE INTO home_post_keywords(post_id,keyword) VALUES(?,?)").bind(Number(s.post_id),w).run();await e.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(id).run();return out(await tg(e,"sendMessage",{chat_id:m.chat.id,text:`✅ ${words.length} کلیدواژه برای پست #${s.post_id} ذخیره شد.\n\nاز «موتور پیشرفته طبقه‌بندی» می‌توانی ادامه بدهی.`}))}return out({ok:true})}
 const d=String(q.data||"");await tg(e,"answerCallbackQuery",{callback_query_id:q.id});
 if(d==="classification_engine")return render(e,q);
 if(d==="ce_toggle"){const s=await setting(e);await e.DB.prepare("UPDATE classification_settings SET enabled=? WHERE id=1").bind(s.enabled?0:1).run();return render(e,q);}
 if(d.startsWith("ce_cat:"))return catMenu(e,q,Number(d.split(":")[1]));
 if(d.startsWith("ce_kw:"))return keywordPrompt(e,q,Number(d.split(":")[1]));
 if(d.startsWith("ce_deleted:")){const n=Number(d.split(":")[1]);await e.DB.prepare("INSERT OR REPLACE INTO home_archive_posts(message_id,channel,url,status,updated_at) VALUES(?,?,?,'deleted',CURRENT_TIMESTAMP)").bind(n,HOME,`https://t.me/${HOME}/${n}`).run();await e.DB.prepare("UPDATE classification_settings SET last_message_id=?,next_message_id=? WHERE id=1").bind(n,n+1).run();return render(e,q);}
 if(d.startsWith("ce_setcat:")){const [,id,cid]=d.split(":").map(Number);const old=await e.DB.prepare("SELECT 1 FROM home_post_categories WHERE post_id=? AND category_id=?").bind(id,cid).first();if(old)await e.DB.prepare("DELETE FROM home_post_categories WHERE post_id=? AND category_id=?").bind(id,cid).run();else await e.DB.prepare("INSERT OR IGNORE INTO home_post_categories(post_id,category_id) VALUES(?,?)").bind(id,cid).run();await e.DB.prepare("INSERT OR REPLACE INTO home_archive_posts(message_id,channel,url,status,updated_at) VALUES(?,?,?,'classified',CURRENT_TIMESTAMP)").bind(id,HOME,`https://t.me/${HOME}/${id}`).run();return catMenu(e,q,id);}
 if(d.startsWith("ce_future:")){const n=Number(d.split(":")[1]);await e.DB.prepare("INSERT OR REPLACE INTO home_archive_posts(message_id,channel,url,status,future_dossier,updated_at) VALUES(?,?,?,'classified',1,CURRENT_TIMESTAMP)").bind(n,HOME,`https://t.me/${HOME}/${n}`).run();await e.DB.prepare("UPDATE classification_settings SET last_message_id=?,next_message_id=? WHERE id=1").bind(n,n+1).run();return render(e,q);}
 if(d.startsWith("ce_next:")){const n=Number(d.split(":")[1])+1;await e.DB.prepare("UPDATE classification_settings SET next_message_id=? WHERE id=1").bind(n).run();return render(e,q);}
 if(d.startsWith("ce_prev:")){const n=Math.max(1,Number(d.split(":")[1])-1);await e.DB.prepare("UPDATE classification_settings SET next_message_id=? WHERE id=1").bind(n).run();return render(e,q);}
 if(d.startsWith("ce_back:"))return render(e,q);
 return out({ok:true})}};
