const tg=async(e,m,b={})=>(await fetch(`https://api.telegram.org/bot${e.BOT_TOKEN}/${m}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)})).json();
const out=x=>new Response(JSON.stringify(x??{ok:true}),{status:200,headers:{"content-type":"application/json"}});
const ensureResponse=async p=>{const r=await p;return r instanceof Response?r:out(r)};
const admin=(e,id)=>String(e.ADMIN_ID||"").split(",").map(x=>x.trim()).filter(Boolean).includes(String(id));
const link=t=>{const s=String(t||"").trim().replace(/[?#].*/,"").replace(/\/$/,"");let m=s.match(/^(?:https?:\/\/)?(?:www\.)?(?:t\.me|telegram\.me)\/c\/(\d+)\/(\d+)$/i);if(m)return{channel:`-100${m[1]}`,post_id:Number(m[2])};m=s.match(/^(?:https?:\/\/)?(?:www\.)?(?:t\.me|telegram\.me)\/(?:s\/)?([A-Za-z0-9_]+)\/(\d+)$/i);return m?{channel:m[1],post_id:Number(m[2])}:null};
const forwardedSource=m=>{const o=m?.forward_origin;if(o&&(o.type==="channel"||o.type==="channel_message")&&o.message_id!=null){const c=o.chat?.username||o.chat?.id;return c!=null?{channel:c,post_id:Number(o.message_id)}:null}if(m?.forward_from_chat&&m?.forward_from_message_id!=null){const c=m.forward_from_chat.username||m.forward_from_chat.id;return c!=null?{channel:c,post_id:Number(m.forward_from_message_id)}:null}return null};
async function hasActiveAdminSession(e,id){if(!admin(e,id))return false;try{const s=await e.DB.prepare("SELECT step,updated_at FROM sessions WHERE user_id=?").bind(id).first();if(!s?.step)return false;if(!s.updated_at)return true;const t=Date.parse(String(s.updated_at).replace(" ","T")+"Z");return !Number.isNaN(t)&&Date.now()-t<30*60*1000}catch{return false}}
async function isFlashSession(e,id){if(!admin(e,id))return false;try{const s=await e.DB.prepare("SELECT step FROM sessions WHERE user_id=?").bind(id).first();return !!s?.step&&String(s.step).startsWith("FLASH_")}catch{return false}}
async function routeCallback(req,e,ctx,u){const q=u?.callback_query;if(!q)return null;const id=q.from?.id,d=String(q.data||"");if((d==="add"||d==="edit")&&admin(e,id))return ensureResponse(import("./flashcard-gate.js").then(x=>x.default.fetch(req,e,ctx)));if(d==="panel"&&admin(e,id))return ensureResponse(import("./admin-panel.js").then(x=>x.default.fetch(req,e,ctx)));if(d==="help"||d==="public_start")return ensureResponse(import("./start-handler.js").then(x=>x.default.fetch(req,e,ctx)));if(d==="public_list:0:0")return ensureResponse(import("./flashcard-public-list-gate.js").then(x=>x.default.fetch(req,e,ctx)));if(d==="public_list"||d.startsWith("public_list:"))return ensureResponse(import("./public-list-handler.js").then(x=>x.default.fetch(req,e,ctx)));if(d==="book_index"||d.startsWith("book:")||d.startsWith("book_index:")||d==="book_noop")return ensureResponse(import("./public-book-gate.js").then(x=>x.default.fetch(req,e,ctx)));if(d.startsWith("flashpub:"))return ensureResponse(import("./flashcard-public-list-gate.js").then(x=>x.default.fetch(req,e,ctx)));if(d.startsWith("flash:")||d.startsWith("flash_index:")||d==="flash_noop")return ensureResponse(import("./flashcard-gate.js").then(x=>x.default.fetch(req,e,ctx)));if(admin(e,id))return ensureResponse(import("./fix-router.js").then(x=>x.default.fetch(req,e,ctx)));if(d==="public_list_noop"){await tg(e,"answerCallbackQuery",{callback_query_id:q.id});return out({ok:true})}if(d==="request_info")return ensureResponse(import("./home-gate.js").then(x=>x.default.fetch(req,e,ctx)));await tg(e,"answerCallbackQuery",{callback_query_id:q.id});return out({ok:true})}
async function route(req,e,ctx,u){const cb=await routeCallback(req,e,ctx,u);if(cb)return cb;const m=u?.message;if(!m)return out({ok:true});if(String(m.text||"").trim()==="/start")return ensureResponse(import("./start-handler.js").then(x=>x.default.fetch(req,e,ctx)));if(String(m.text||"").trim()==="/admin"){if(!admin(e,m.from?.id))return out(await tg(e,"sendMessage",{chat_id:m?.chat?.id,text:"⚠️ <b>دسترسی ندارید.</b>",parse_mode:"HTML"}));return ensureResponse(import("./admin-panel.js").then(x=>x.default.fetch(req,e,ctx)))}const direct=link(m.text||m.caption||"");const fs=forwardedSource(m);const active=admin(e,m.from?.id)&&await hasActiveAdminSession(e,m.from?.id);if(admin(e,m.from?.id)&&await isFlashSession(e,m.from?.id))return ensureResponse(import("./flashcard-gate.js").then(x=>x.default.fetch(req,e,ctx)));if(!admin(e,m.from?.id)&&(direct||fs))return ensureResponse(import("./flashcard-gate.js").then(x=>x.default.fetch(req,e,ctx)));const publicLink=direct||(fs?`https://t.me/${String(fs.channel).replace(/^@/,"")}/${fs.post_id}`:null);const patched=publicLink?new Request(req.url,{method:"POST",headers:req.headers,body:JSON.stringify({...u,message:{...m,text:publicLink,entities:[]}})}):req;if(publicLink&&!active)return ensureResponse(import("./public-delivery.js").then(x=>x.default.fetch(patched,e,ctx)));if(!admin(e,m.from?.id))return out({ok:true});return ensureResponse(import("./fix-router.js").then(x=>x.default.fetch(patched,e,ctx)))}
export default{async fetch(req,e,ctx){if(req.method!=="POST")return out({ok:true});let u;try{u=await req.clone().json()}catch{return out({ok:true})}try{return await ensureResponse(route(req,e,ctx,u))}catch(err){console.error("[CERCIS_ROUTER]",err);const q=u?.callback_query;if(q?.id){try{await tg(e,"answerCallbackQuery",{callback_query_id:q.id,text:"⚠️ خطای موقت. لطفاً دوباره تلاش کنید."})}catch{}}return out({ok:true})}};