const HOME_CHANNEL="Arghavanplaylistt";
const tg=async(e,m,b={})=>(await fetch(`https://api.telegram.org/bot${e.BOT_TOKEN}/${m}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)})).json();
const response=(x)=>new Response(JSON.stringify(x),{status:200,headers:{"content-type":"application/json"}});
const normalizeChannel=c=>String(c??"").replace(/^@/,"").trim().toLowerCase();
const isHome=c=>normalizeChannel(c)===HOME_CHANNEL.toLowerCase();
const parseLink=t=>{const m=String(t||"").trim().match(/^https?:\/\/t\.me\/(?:c\/)?([A-Za-z0-9_]+)\/([0-9]+)(?:\?.*)?$/);return m?{channel:m[1],post_id:Number(m[2])}:null};
const isChannelForward=m=>m?.forward_origin?.type==="channel"||m?.forward_origin?.type==="channel_message";
const forwardedPost=m=>{if(!isChannelForward(m)||m.forward_origin?.message_id==null)return null;const c=m.forward_origin.chat;return{channel:c?.username||c?.id,post_id:Number(m.forward_origin.message_id)}};
const isAdmin=(e,id)=>String(e.ADMIN_ID||"").split(",").map(x=>x.trim()).filter(Boolean).includes(String(id));
const trackUser=async(e,id)=>{if(id!=null)await e.DB.prepare("INSERT OR IGNORE INTO users(user_id) VALUES(?)").bind(id).run()};
const track=async(e,c,p)=>{const n=normalizeChannel(c);return e.DB.prepare("SELECT * FROM tracks WHERE lower(replace(channel,'@',''))=? AND post_id=? ORDER BY id DESC LIMIT 1").bind(n,Number(p)).first()};
const parts=v=>{try{const x=JSON.parse(v||"[]");return Array.isArray(x)?x.filter(p=>p.text||p.media_file_id):[]}catch{return[]}};
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
async function sendPage(e,c,id,page=1){const r=await e.DB.prepare("SELECT id,title,details2 FROM tracks WHERE id=?").bind(id).first();const ps=parts(r?.details2);if(!r||!ps.length)return response({ok:true});const i=Math.min(Math.max(Number(page)||1,1),ps.length)-1,p=ps[i];const rows=[];if(i>0)rows.push({text:`‹ ${i}/${ps.length}`,callback_data:`book:${id}:${i}`});else rows.push({text:`• 1/${ps.length}`,callback_data:"book_noop"});if(i<ps.length-1)rows.push({text:`${i+2}/${ps.length} ›`,callback_data:`book:${id}:${i+2}`});else rows.push({text:`${ps.length}/${ps.length} •`,callback_data:"book_noop"});const markup={inline_keyboard:[rows,[{text:"📖 فهرست پرونده",callback_data:`book_index:${id}`}]]};if(p.media_file_id){const method={photo:"sendPhoto",video:"sendVideo",audio:"sendAudio",voice:"sendVoice"}[p.media_type]||"sendPhoto";const b={chat_id:c,[p.media_type||"photo"]:p.media_file_id,caption:p.caption||"",reply_markup:markup};if(p.caption_entities?.length)b.caption_entities=p.caption_entities;else if(p.caption)b.parse_mode="HTML";await tg(e,method,b);return response({ok:true})}if(p.entities?.length){await tg(e,"sendMessage",{chat_id:c,text:p.text||"",entities:p.entities,reply_markup:markup});return response({ok:true})}await tg(e,"sendMessage",{chat_id:c,text:`${p.text||""}\n\n📖 <b>صفحه ${i+1} از ${ps.length}</b>`,parse_mode:"HTML",reply_markup:markup});return response({ok:true})}
export {HOME_CHANNEL,normalizeChannel,isHome,parseLink,isChannelForward,forwardedPost,isAdmin,trackUser,track,parts,sendPage};
