const tg=async(e,m,b={})=>(await fetch("https://api.telegram.org/bot"+e.BOT_TOKEN+"/"+m,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)})).json();
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");
async function hmac(key,data){const k=await crypto.subtle.importKey("raw",key,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return crypto.subtle.sign("HMAC",k,new TextEncoder().encode(data))}
async function auth(req,e){const raw=req.headers.get("x-telegram-init-data")||"";if(!raw||!e.BOT_TOKEN)return null;const p=new URLSearchParams(raw),hash=p.get("hash");if(!hash)return null;const pairs=[];p.forEach((v,k)=>{if(k!=="hash"&&k!=="signature")pairs.push([k,v])});pairs.sort((a,b)=>a[0].localeCompare(b[0]));const data=pairs.map(x=>x[0]+"="+x[1]).join("\n");const secret=await hmac(new TextEncoder().encode(e.BOT_TOKEN),"WebAppData");const check=hex(await hmac(new Uint8Array(secret),data));if(check!==hash)return null;const age=Math.floor(Date.now()/1000)-Number(p.get("auth_date")||0);if(!Number.isFinite(age)||age<0||age>86400)return null;try{return JSON.parse(p.get("user")||"{}")}catch{return null}}
async function schema(e){await e.DB.prepare("CREATE TABLE IF NOT EXISTS quiz_questions(id TEXT PRIMARY KEY,text TEXT NOT NULL,options TEXT NOT NULL,correct_answers TEXT NOT NULL,xp INTEGER NOT NULL DEFAULT 10,active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();await e.DB.prepare("CREATE TABLE IF NOT EXISTS quiz_question_cases(question_id TEXT NOT NULL,track_id INTEGER NOT NULL,position INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(question_id,track_id))").run();await e.DB.prepare("CREATE TABLE IF NOT EXISTS quiz_case_deliveries(user_id INTEGER NOT NULL,question_id TEXT NOT NULL,track_id INTEGER NOT NULL,delivered_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,question_id,track_id))").run()}
async function sendPage(e,c,id){const r=await e.DB.prepare("SELECT id,title,details2 FROM tracks WHERE id=?").bind(id).first();if(!r)return false;let ps=[];try{ps=JSON.parse(r.details2||"[]")}catch{}ps=Array.isArray(ps)?ps.filter(x=>x&&(x.text||x.caption||x.media_file_id||x.source_message_id)):[];if(!ps.length)return false;const p=ps[0],rm={inline_keyboard:[[ps.length>1?{text:"2/"+ps.length+" ›",callback_data:"book:"+id+":2"}:{text:"1/1",callback_data:"book_noop"}],[{text:"📜 فهرست پرونده‌های ثبت‌شده",callback_data:"public_list"}]]},b={chat_id:c,reply_markup:rm};if(p.source_message_id){await tg(e,"copyMessage",{chat_id:c,from_chat_id:p.source_chat_id,message_id:p.source_message_id,reply_markup:rm});return true}if(p.media_file_id){const mm={photo:"sendPhoto",video:"sendVideo",audio:"sendAudio",voice:"sendVoice",document:"sendDocument",animation:"sendAnimation"}[p.media_type];if(!mm)return false;await tg(e,mm,{chat_id:c,[p.media_type]:p.media_file_id,caption:p.caption||"",caption_entities:p.caption_entities?.length?p.caption_entities:undefined,reply_markup:rm});return true}await tg(e,"sendMessage",{chat_id:c,text:p.text||"",entities:p.entities?.length?p.entities:undefined,parse_mode:p.entities?.length?undefined:"HTML",reply_markup:rm});return true}
export default{async fetch(req,e){if(!["GET","POST"].includes(req.method))return json({ok:false},405);await schema(e);const u=await auth(req,e);if(!u?.id)return json({ok:false,error:"unauthorized"},401);const path=new URL(req.url).pathname;
if(path==="/api/quiz/questions"&&req.method==="GET"){const rows=(await e.DB.prepare("SELECT q.id,q.text,q.options,q.correct_answers,q.xp,q.difficulty,EXISTS(SELECT 1 FROM quiz_question_cases c WHERE c.question_id=q.id) has_cases FROM quiz_questions q WHERE q.active=1 ORDER BY q.id").all()).results||[];return json({ok:true,questions:rows.map(r=>({id:r.id,text:r.text,options:JSON.parse(r.options||"[]"),correctAnswers:JSON.parse(r.correct_answers||"[]"),xp:Number(r.xp)||0,difficulty:r.difficulty||"medium",hasCases:Boolean(r.has_cases)}))})}
if(path==="/api/quiz/case"&&req.method==="POST"){let b;try{b=await req.json()}catch{return json({ok:false,error:"bad_json"},400)}const qid=String(b?.questionId||"");if(!qid)return json({ok:false,error:"missing_question"},400);const qs=(await e.DB.prepare("SELECT track_id FROM quiz_question_cases WHERE question_id=? ORDER BY position").bind(qid).all()).results||[];if(!qs.length)return json({ok:true,received:0});let received=0;for(const x of qs){const tid=Number(x.track_id),exists=await e.DB.prepare("SELECT 1 FROM quiz_case_deliveries WHERE user_id=? AND question_id=? AND track_id=?").bind(u.id,qid,tid).first();if(exists)continue;const ok=await sendPage(e,u.id,tid);if(ok){await e.DB.prepare("INSERT OR IGNORE INTO quiz_case_deliveries(user_id,question_id,track_id) VALUES(?,?,?)").bind(u.id,qid,tid).run();received++}}return json({ok:true,received})}
return json({ok:false,error:"not_found"},404)}};
