const tg=async(e,m,b={})=>(await fetch("https://api.telegram.org/bot"+e.BOT_TOKEN+"/"+m,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)})).json();
const resp=x=>new Response(JSON.stringify(x),{status:200,headers:{"content-type":"application/json"}});
const admin=(e,id)=>String(e.ADMIN_ID||"").split(",").map(x=>x.trim()).filter(Boolean).includes(String(id));
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const PAGE=8;
async function schema(e){await e.DB.prepare("CREATE TABLE IF NOT EXISTS quiz_questions(id TEXT PRIMARY KEY,text TEXT NOT NULL,options TEXT NOT NULL,correct_answers TEXT NOT NULL,xp INTEGER NOT NULL DEFAULT 10,active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();await e.DB.prepare("CREATE TABLE IF NOT EXISTS quiz_question_cases(question_id TEXT NOT NULL,track_id INTEGER NOT NULL,position INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(question_id,track_id))").run();await e.DB.prepare("CREATE TABLE IF NOT EXISTS quiz_admin_sessions(user_id INTEGER PRIMARY KEY,step TEXT NOT NULL,payload TEXT,control_message_id INTEGER,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();}
const payload=s=>{try{return JSON.parse(s?.payload||"{}")}catch{return{}}};
async function sess(e,id){return e.DB.prepare("SELECT * FROM quiz_admin_sessions WHERE user_id=?").bind(id).first()}
async function save(e,id,step,p,mid){return e.DB.prepare("INSERT INTO quiz_admin_sessions(user_id,step,payload,control_message_id,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET step=excluded.step,payload=excluded.payload,control_message_id=excluded.control_message_id,updated_at=CURRENT_TIMESTAMP").bind(id,step,JSON.stringify(p||{}),mid||null).run()}
async function clear(e,id){return e.DB.prepare("DELETE FROM quiz_admin_sessions WHERE user_id=?").bind(id).run()}
async function edit(e,q,text,markup){return resp(await tg(e,"editMessageText",{chat_id:q.message.chat.id,message_id:q.message.message_id,text,parse_mode:"HTML",reply_markup:markup}))}
const menu={inline_keyboard:[[{text:"➕ ثبت سوال",callback_data:"quiz_add"}],[{text:"📋 سوال‌های ثبت‌شده",callback_data:"quiz_list:1"}],[{text:"🔙 پنل مدیریت",callback_data:"panel"}]]};
const cancel=cb=>({inline_keyboard:[[{text:"❌ لغو",callback_data:"quiz_cancel"}],[{text:"🔙 پنل مدیریت",callback_data:cb||"panel"}]]});
function parseCorrect(v){const s=String(v||"").trim().toLowerCase();if(["0","none","هیچ","هیچکدام","هیچ‌کدام"].includes(s))return[];const a=s.split(/[,،\s]+/).filter(Boolean).map(Number);if(!a.length||a.some(n=>![1,2,3].includes(n)))return null;return[...new Set(a)].sort((a,b)=>a-b).map(n=>n-1)}
async function detail(e,r){const o=JSON.parse(r.options||"[]"),ca=JSON.parse(r.correct_answers||"[]"),cs=(await e.DB.prepare("SELECT t.id,t.title FROM quiz_question_cases c JOIN tracks t ON t.id=c.track_id WHERE c.question_id=? ORDER BY c.position").bind(r.id).all()).results||[];return "🧠 <b>"+esc(r.id)+"</b>\n\n<b>"+esc(r.text)+"</b>\n\n1. "+esc(o[0]||"")+"\n2. "+esc(o[1]||"")+"\n3. "+esc(o[2]||"")+"\n\n<b>پاسخ صحیح:</b> "+(ca.length?ca.map(x=>x+1).join("، "):"هیچ‌کدام")+"\n<b>XP:</b> "+r.xp+"\n<b>پرونده‌ها:</b> "+(cs.length?cs.map(x=>"#"+x.id+" "+esc(x.title||"پرونده")).join(" | "):"بدون پرونده")}
async function home(e,q){return edit(e,q,"🧠 <b>مدیریت سوال‌های CERCIS</b>\n\nثبت، مشاهده، ویرایش سوال و اتصال یک یا چند پرونده.",menu)}
async function list(e,q,page){const n=Number((await e.DB.prepare("SELECT COUNT(*) n FROM quiz_questions").first())?.n||0),total=Math.max(1,Math.ceil(n/PAGE)),p=Math.min(Math.max(Number(page)||1,1),total),rows=(await e.DB.prepare("SELECT id,text,xp FROM quiz_questions ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?").bind(PAGE,(p-1)*PAGE).all()).results||[];let t="📋 <b>سوال‌های ثبت‌شده</b>\n\n"+n+" سوال — صفحه "+p+" از "+total+"\n\n";for(let i=0;i<rows.length;i++)t+=(p-1)*PAGE+i+1+". <b>"+esc(String(rows[i].text).slice(0,100))+"</b> — "+rows[i].xp+" XP\n";const kb=rows.map(r=>[{text:"✏️ "+String(r.text).slice(0,45),callback_data:"quiz_view:"+r.id}]);const nav=[];if(p>1)nav.push({text:"‹",callback_data:"quiz_list:"+(p-1)});if(p<total)nav.push({text:"›",callback_data:"quiz_list:"+(p+1)});if(nav.length)kb.push(nav);kb.push([{text:"➕ ثبت سوال",callback_data:"quiz_add"}],[{text:"🔙 مدیریت سوال‌ها",callback_data:"quiz_panel"}]);return edit(e,q,t,{inline_keyboard:kb})}
async function view(e,q,id){const r=await e.DB.prepare("SELECT * FROM quiz_questions WHERE id=?").bind(id).first();if(!r)return edit(e,q,"❌ سوال پیدا نشد.",{inline_keyboard:[[{text:"🔙 فهرست",callback_data:"quiz_list:1"}]]});return edit(e,q,await detail(e,r),{inline_keyboard:[[{text:"✏️ متن",callback_data:"quiz_edit_text:"+id},{text:"✏️ گزینه‌ها",callback_data:"quiz_edit_options:"+id}],[{text:"✏️ پاسخ",callback_data:"quiz_edit_correct:"+id},{text:"✏️ XP",callback_data:"quiz_edit_xp:"+id}],[{text:"📚 پرونده‌ها",callback_data:"quiz_edit_cases:"+id}],[{text:"🔙 فهرست",callback_data:"quiz_list:1"}]]})}
async function start(e,q,step,id,prompt){await save(e,q.from.id,step,id?{id}: {},q.message.message_id);return edit(e,q,prompt,cancel("quiz_panel"))}
async function picker(e,q,id){const rows=(await e.DB.prepare("SELECT id,title FROM tracks WHERE COALESCE(display_mode,'book')='book' ORDER BY id DESC LIMIT 40").all()).results||[],sel=(await e.DB.prepare("SELECT track_id FROM quiz_question_cases WHERE question_id=?").bind(id).all()).results||[],set=new Set(sel.map(x=>Number(x.track_id)));const kb=rows.map(r=>[{text:(set.has(Number(r.id))?"☑️ ":"⬜ ")+String(r.title||("پرونده #"+r.id)).slice(0,48),callback_data:"quiz_case_toggle:"+id+":"+r.id}]);kb.push([{text:"✅ ذخیره پرونده‌ها",callback_data:"quiz_case_done:"+id}],[{text:"⏭ بدون پرونده",callback_data:"quiz_case_none:"+id}],[{text:"❌ لغو",callback_data:"quiz_cancel"}]);return edit(e,q,"📚 <b>پرونده‌های متصل به سوال</b>\n\nیک یا چند پرونده را انتخاب کن.\n☑️ = انتخاب‌شده",{inline_keyboard:kb})}
async function finish(e,q,id){await clear(e,q.from.id);const r=await e.DB.prepare("SELECT * FROM quiz_questions WHERE id=?").bind(id).first();return edit(e,q,"✅ <b>ذخیره شد.</b>\n\n"+await detail(e,r),{inline_keyboard:[[{text:"✏️ ویرایش",callback_data:"quiz_view:"+id}],[{text:"📋 فهرست",callback_data:"quiz_list:1"}],[{text:"🧠 مدیریت سوال‌ها",callback_data:"quiz_panel"}]]})}
async function message(e,m){const s=await sess(e,m.from.id);if(!s)return null;const p=payload(s),v=String(m.text||"").trim();
if(s.step==="ADD_TEXT"){if(!v)return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ متن سوال خالی است."}));p.text=v;await save(e,m.from.id,"ADD_OPTIONS",p,s.control_message_id);return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"۳ گزینه را دقیقاً در ۳ خط بفرست."}))}
if(s.step==="ADD_OPTIONS"){const o=v.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(o.length!==3)return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ دقیقاً ۳ گزینه لازم است."}));p.options=o;await save(e,m.from.id,"ADD_CORRECT",p,s.control_message_id);return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"شماره گزینه‌های صحیح را بفرست؛ مثل 1 یا 1,2. برای هیچ‌کدام 0."}))}
if(s.step==="ADD_CORRECT"){const c=parseCorrect(v);if(c===null)return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ مقدار نامعتبر است."}));p.correct=c;await save(e,m.from.id,"ADD_XP",p,s.control_message_id);return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"XP سوال را بفرست؛ مثلاً 10 یا 15."}))}
if(s.step==="ADD_XP"){const xp=Number(v);if(!Number.isInteger(xp)||xp<0||xp>10000)return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ XP باید عدد صحیح بین 0 تا 10000 باشد."}));const id="q_"+Date.now()+"_"+crypto.randomUUID().slice(0,8);await e.DB.prepare("INSERT INTO quiz_questions(id,text,options,correct_answers,xp) VALUES(?,?,?,?,?)").bind(id,p.text,JSON.stringify(p.options),JSON.stringify(p.correct),xp).run();return picker(e,{...m,message:{chat:id,message_id:s.control_message_id}},id)}
if(["EDIT_TEXT","EDIT_OPTIONS","EDIT_CORRECT","EDIT_XP"].includes(s.step)){const r=await e.DB.prepare("SELECT * FROM quiz_questions WHERE id=?").bind(p.id).first();if(!r)return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ سوال پیدا نشد."}));if(s.step==="EDIT_TEXT"){if(!v)return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ متن خالی است."}));await e.DB.prepare("UPDATE quiz_questions SET text=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(v,p.id).run()}else if(s.step==="EDIT_OPTIONS"){const o=v.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(o.length!==3)return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ دقیقاً ۳ گزینه لازم است."}));await e.DB.prepare("UPDATE quiz_questions SET options=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(JSON.stringify(o),p.id).run()}else if(s.step==="EDIT_CORRECT"){const c=parseCorrect(v);if(c===null)return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ پاسخ نامعتبر است."}));await e.DB.prepare("UPDATE quiz_questions SET correct_answers=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(JSON.stringify(c),p.id).run()}else{const xp=Number(v);if(!Number.isInteger(xp)||xp<0||xp>10000)return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"❌ XP نامعتبر است."}));await e.DB.prepare("UPDATE quiz_questions SET xp=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(xp,p.id).run()}await clear(e,m.from.id);return resp(await tg(e,"sendMessage",{chat_id:m.chat.id,text:"✅ تغییرات ذخیره شد.",reply_markup:{inline_keyboard:[[{text:"✏️ بازگشت به سوال",callback_data:"quiz_view:"+p.id}]]}}))}
return null}
export default{async fetch(req,e){if(req.method!=="POST")return resp({ok:true});let u;try{u=await req.clone().json()}catch{return resp({ok:true})}const q=u?.callback_query,m=u?.message,id=q?.from?.id||m?.from?.id;if(!admin(e,id))return resp({ok:true});await schema(e);if(q?.id)await tg(e,"answerCallbackQuery",{callback_query_id:q.id});const d=String(q?.data||"");
if(d==="quiz_panel")return home(e,q);if(d==="quiz_add")return start(e,q,"ADD_TEXT",null,"➕ <b>ثبت سوال</b>\n\nمتن سوال را ارسال کن.");if(d==="quiz_cancel"){await clear(e,id);return home(e,q)}if(d.startsWith("quiz_list:"))return list(e,q,d.split(":")[1]);if(d.startsWith("quiz_view:"))return view(e,q,d.slice(10));if(d.startsWith("quiz_edit_text:"))return start(e,q,"EDIT_TEXT",d.slice(15),"✏️ <b>متن جدید سوال</b>\n\nارسال کن.");if(d.startsWith("quiz_edit_options:"))return start(e,q,"EDIT_OPTIONS",d.slice(18),"✏️ <b>گزینه‌های جدید</b>\n\n۳ خط ارسال کن.");if(d.startsWith("quiz_edit_correct:"))return start(e,q,"EDIT_CORRECT",d.slice(18),"✏️ <b>پاسخ صحیح جدید</b>\n\nمثل 1,2 یا 0.");if(d.startsWith("quiz_edit_xp:"))return start(e,q,"EDIT_XP",d.slice(13),"✏️ <b>XP جدید</b>\n\nعدد را ارسال کن.");if(d.startsWith("quiz_edit_cases:"))return picker(e,q,d.slice(16));if(d.startsWith("quiz_case_toggle:")){const a=d.split(":");const x=await e.DB.prepare("SELECT 1 FROM quiz_question_cases WHERE question_id=? AND track_id=?").bind(a[1],Number(a[2])).first();if(x)await e.DB.prepare("DELETE FROM quiz_question_cases WHERE question_id=? AND track_id=?").bind(a[1],Number(a[2])).run();else{const n=Number((await e.DB.prepare("SELECT COUNT(*) n FROM quiz_question_cases WHERE question_id=?").bind(a[1]).first())?.n||0);await e.DB.prepare("INSERT OR IGNORE INTO quiz_question_cases(question_id,track_id,position) VALUES(?,?,?)").bind(a[1],Number(a[2]),n+1).run()}return picker(e,q,a[1])}if(d.startsWith("quiz_case_done:"))return finish(e,q,d.slice(15));if(d.startsWith("quiz_case_none:")){await e.DB.prepare("DELETE FROM quiz_question_cases WHERE question_id=?").bind(d.slice(15)).run();return finish(e,q,d.slice(15))}if(m)return(await message(e,m))||resp({ok:true});return resp({ok:true})}};
